version: 2
updates:
  - package-ecosystem: github-actions
    directory: ""
    target-branch: develop
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: terraform/team
    target-branch: develop
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: GameBot
    target-branch: develop
    schedule:
      interval: daily
